
require(reshape2)
require(ggplot2)


## Make a set of labels for the breaks derived from a histogram function.
## These labels can be applied to data that is generated by the cut function.
make_break_labels <- function(name, breaks, sep="x") {
  n <- length(breaks)
  m <- n - 1
  sapply(1:m, function(i) {
    j <- i + 1
    lower <- breaks[[i]]
    upper <- breaks[[j]]
    low <- if (lower < 0) {
      paste0("minus", abs(lower))
    } else as.character(lower)
    up <- if (upper < 0) {
      paste0("minus", abs(upper))
    } else as.character(upper)
    
    name <- paste(name, low, up, sep=sep)
    name
  })
}
## Compute the X frequency matrix, Y frequency matrix
## Joint P(A AND B)
## Conditional P_r = P(B given A)
## Condition P_s = P(A given B)
compute_tables <- function(data, col1name, col2name) {
  
  ## XMat is the matrix A_i counts
  form1 <- as.formula(paste0("~ ", col1name, " - 1"))
  Xmat <- model.matrix(form1, data)
  
  ## YMat is the matrix B_j counts
  form2 <- as.formula(paste0("~ ", col2name, " - 1"))
  Ymat <- model.matrix(form2, data)
  
  
  ## We can build the 2 way contingency table of each class
  ## Rows A_i cols B_j
  two_way_table <- t(as.matrix(Xmat)) %*% as.matrix(Ymat)
  
  ## Estimates for frequencies
  
  n <- sum(two_way_table)
  
  ## Total frequencies of X matrix
  D_r <- 1/n * (t(Xmat) %*% Xmat)
  
  ## Total frequencies of Y matrix
  D_s <- 1/n * (t(Ymat) %*% Ymat)
  
  ## UMV estimateion of $P_{ij}$ joint distribution of pairs of variables.
  P_joint <- 1/n * two_way_table
  
  ## Conditional probability that an individual has property B_j given they have property A_i
  ## P_r <- D_r^{-1}P
  P_r <- ginv(D_r)%*%P_joint
  row.names(P_r) <- row.names(P_joint)
  
  ## Conditional probability of A_i given B_j
  P_s <- ginv(D_s)%*%t(P_joint)
  row.names(P_s) <- colnames(P_joint)
  
  list(
    X=Xmat,
    Y=Ymat,
    n=n,
    D_r=D_r,
    D_s=D_s,
    P_joint=P_joint,
    P_r=P_r,
    P_s=P_s
  )
}


display_table <- function(mat, title,legend_title) {
  
  display <- melt(mat)
  
  labels <- round(display$value,2)
  idx <- which(labels == 0)
  labels[idx] <- NA
  
  ggplot(data = display, aes(Var2, Var1, fill = value))+
    geom_tile(color = "white")+
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                         midpoint = 0, limit = c(0,1), space = "Lab", 
                         name=legend_title) +
    theme_minimal()+ 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                     size = 12, hjust = 1))+
    coord_fixed() +
    geom_text(aes(Var2, Var1), label = labels, color = "black", size = 4) +
    theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank()) + 
    ggtitle(title)
  
}